//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Services.Resources
{
    using System;
    using System.Reflection;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotificationTemplates
    {
        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationTemplates()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Services.Resources.NotificationTemplates", typeof(NotificationTemplates).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }



        /// <summary>
        ///   Looks up a localized string similar to We have received your donation of {{Amount}} to {{CampaignName}}. Receipt No: {{ReceiptNumber}}.
        /// </summary>
        internal static string DonationReceipt_Body
        {
            get
            {
                return ResourceManager.GetString("DonationReceipt_Body", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Thank you for your donation {{DonorName}}.
        /// </summary>
        internal static string DonationReceipt_Subject
        {
            get
            {
                return ResourceManager.GetString("DonationReceipt_Subject", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Campaign {{CampaignName}} Goal Reached.
        /// </summary>
        internal static string CampaignGoalReached_Subject
        {
            get
            {
                return ResourceManager.GetString("CampaignGoalReached_Subject", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to We are pleased to inform you that the campaign {{CampaignName}} has reached its funding goal.
        /// </summary>
        internal static string CampaignGoalReached_Body
        {
            get
            {
                return ResourceManager.GetString("CampaignGoalReached_Body", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Welcome to Donation Platform.
        /// </summary>
        internal static string Register_Subject
        {
            get
            {
                return ResourceManager.GetString("Register_Subject", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hello {{UserName}}, Thank you for registering with our donation platform.
        /// </summary>
        internal static string Register_Body
        {
            get
            {
                return ResourceManager.GetString("Register_Body", resourceCulture);
            }
        }
    }
}
